### ISSUE TITLE
增加工具从制定页面提取所有的host

### ISSUE THREAD

**Issue by LubyRuffy** [LubyRuffy/fofa#14]
比如一些平台会放出有漏洞的host列表，可以批量提取

**Comment by liangt666** [comment]
大牛，请教个一个配置安装问题啊。
rake db:schema:load 报错如下啊
rake aborted!
NoMethodError: undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x000000063f83a0>
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `ensure in with_devise_exclusive_scope'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:457:in `with_devise_exclusive_scope'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:248:in `block (2 levels) in devise_for'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:351:in `block in devise_scope'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `constraints'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:350:in `devise_scope'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:247:in `block in devise_for'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `each'
/usr/local/rvm/gems/ruby-2.0.0-p598/gems/devise-3.3.0/lib/devise/rails/routes.rb:223:in `devise_for'
/root/fofa/fofa-master/config/routes.rb:14:in `block in <top (required)>'


能否帮我看看，是什么地方出了差错呢。

**Comment by liangt666** [comment]
gem 'devise', :git => 'https://github.com/plataformatec/devise.git', :branch => 'lm-rails-4-2' 已经解决。来源地址：https://github.com/plataformatec/devise/issues/3159
